### ISSUE TITLE
QUESTION: What back-end did you used for the web page and server ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [DroneBridge/ESP32#25]
The new web page is flawless.

What back-end did you used for the web page and server ?

**Comment by seeul8er** [comment]
Thank you. Not sure what you mean. The backend is run by the esp-idf HTTP server API. Additionally, it runs a REST:API "server". Most of it is copy&paste from the example project.

The frontend is a website that runs javascript in the background (local in the browser) and requests/posts info to the REST:API. Since this was my first JavaScript Project I used WebStorm IDE to be on the save side. Always nice to have some proper debugging support from the IDE. The rest is just some basic Webdesign and a CSS framework to not have to start at zero.
