### ISSUE TITLE
Feat. Req connect to Internet

### ISSUE THREAD

**Issue by ariefadha** [DroneBridge/ESP32#29]
Can the data push to the Andruav server?
For example the esp32 connect to usb dongle modem instead becaming Access Point mode. And send the data via internet.

**Comment by seeul8er** [comment]
Sure, that would be possible in theory, but it is not supported out of the box. You would need to re-write some of the code that launches the access point and instead make the ESP32 connect to your access point.
The problem is that the access point to connect to will be hardcoded inside the code. So this would be a custom solution for you and you will need to figure it out without my help :)

**Comment by ariefadha** [comment]
No need access point, esp32 act as client and connect to 3g modem (portable)

Watch this video, this guy already made it
https://youtu.be/Tg4JqZFNZJY

**Comment by seeul8er** [comment]
The 3G Router does have an internal access point where the esp would connect to. However you will have to change the code of DroneBridge for ESP32 to be able to do that

**Comment by jpfree** [comment]
so i  also want more network connecting，not just AP mode，like STA or STA+AP

**Comment by jpfree** [comment]
> 

could you release a STA MODE version?  i am fresh for the code ,thanks
