### ISSUE TITLE
API not RESTful

### ISSUE THREAD

**Issue by mmalecki** [DroneBridge/ESP32#74]
While I was working on #73, I noticed that the API (including the one in the v2 dev branch) is not really RESTful. Would you be open to collaborating/merging a PR for making it so?

As an example:
* `GET /api/settings/request` => `GET /api/settings`
* `POST /api/settings/change` => `POST (or PATCH) /api/settings`
to achieve the typical CRUD-over-REST API style,
as well as `GET /api/system/reboot` to `POST /api/system/reboot` to satisfy the RESTful requirement of `GET` requests not having side-effects.

**Comment by seeul8er** [comment]
That sounds like a good idea, if you want please go ahead and fix it in the v2_dev branch. This will becoming the new release

**Comment by mmalecki** [comment]
Thanks @seeul8er. Code changes made in #76, just struggling to find out how to get the frontend built, any advice welcome :).

**Comment by seeul8er** [comment]
Thanks! Unfortunately I have not setup an automated build so far. You have to manually copy & paste the index.html to the frontend folder. 
Then I usually run the `dronebridge.js` content through [minify-js](https://minify-js.com/) and paste it instead of the link to the script. I do the same for CSS content using [minifier](https://www.minifier.org/).

**Comment by seeul8er** [comment]
Fixed with #77
